### ISSUE TITLE
Missing back-link to "Task 1.1: Set Up Environment Variables" (for DTR_URL)

### ISSUE THREAD

**Issue by ericsmalling** [clemenko/jenkinsworld2018#2]
In **Pull / Tag / Push Docker Image** section, back ref to a section that must have been removed (and DTR_URL is not set):

> In the console we should already have a variable called DTR_URL. Lets check.
> 
> echo $DTR_URL
> If you are not sure please follow Task 1.1: Set Up Environment Variables.

**Comment by clemenko** [comment]
fixed in commit https://github.com/clemenko/jenkinsworld2018/commit/613e918a09124daead0a5e0ecfe7a85caddbcfe7
