### ISSUE TITLE
Initial images have no critical vulnerabilities

### ISSUE THREAD

**Issue by ericsmalling** [clemenko/jenkinsworld2018#3]
Not sure it's important to the narrative of the article, but a scan tonight showed only majors, no criticals as shown.

![image](https://user-images.githubusercontent.com/361554/44129608-08f427d0-9ffe-11e8-937a-ddf54844ddf8.png)

**Comment by clemenko** [comment]
I think it is more about showing vulns and the specific type.

**Comment by ericsmalling** [comment]
Ok, wasn't sure if the fact that all pushed immediately get promoted now was a change for the flow of the tutorial.
