### ISSUE TITLE
No image with "promoted" tag

### ISSUE THREAD

**Issue by ericsmalling** [clemenko/jenkinsworld2018#4]
**Docker Content Trust / Image Signing** section says:
> Right now you should have a promoted image $DTR_URL/ci/dc18:promoted. We need to tag it with a new signed tag.
>
> docker tag $DTR_URL/ci/dc18:promoted $DTR_URL/ci/dc18:signed

... but we do not have any image with a "promoted" tag.

**Comment by clemenko** [comment]
Not sure it is needed since we are working with the command line in this section.
